name: magic
channels:
  - pytorch
  - xformers
dependencies:
  - python=3.10
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - cudatoolkit=11.3
  - xformers
  - pip
  - pip:
    - diffusers[torch]==0.22.1
    - transformers==4.29.0
    - imageio==2.27.0
    - torch==1.12.1
    - gdown
    - einops
    - omegaconf
    - safetensors
    - wandb
    - "--editable=git+https://github.com/luca-medeiros/lang-segment-anything.git@134a48a81ebd691686187ecce2d016fb327a8852#egg=lang-sam"